FROM centos
RUN yum install wget -y
RUN wget https://dl.grafana.com/oss/release/grafana-7.0.4.linux-amd64.tar.gz
RUN tar -zxvf grafana-7.0.4.linux-amd64.tar.gz
RUn rm grafana-7.0.4.linux-amd64.tar.gz
RUN mv grafana-7.0.4 /etc/grafana
RUN mv /etc/grafana/bin/grafana-server /usr/sbin/grafana-server
CMD grafana-server --config "/etc/grafana/conf/defaults.ini" --homepath /etc/grafana/
