apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    name: grafana-port-expose
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30188
      name: grafana
  selector:
    app: grafana-server
