apiVersion: v1
kind: Service
metadata:
  name: pv-pod
  labels:
    name: apache-port-expose
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 30189
      name: http
  selector:
    app: prometheus-server
